### ISSUE TITLE
How to setVisibility batteryTimeLayout when FULLSCREEN

### ISSUE THREAD

**Issue by fongfuse** [lipangit/JieCaoVideoPlayer#1117]
I want to setVisibility batteryTimeLayout  is Gone when currentScreen==SCREEN_WINDOW_FULLSCREEN

and I try

 ```
 jcVideoPlayerStandard.fullscreenButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (jcVideoPlayerStandard.currentScreen == SCREEN_LAYOUT_NORMAL){
                    jcVideoPlayerStandard.batteryTimeLayout.setVisibility(View.GONE);
                    jcVideoPlayerStandard.startWindowFullscreen();
                }
            }
        });

```
is  not work

**Comment by Seamo** [comment]
Seems that you want to hide "batteryTimeLayout"(guess a custom layout?) when into fullscreen. Look at function startWindowFullScreen(). It will create a new jcmediaplayer instance, a new textureview, and add it to current viewgroup. Your layout is visible default, So it is displayed.
The problem is, you hide that layout too early.
Try hide layout after startWindowFullScreen() may solve that, but I DON'T think its a good choice. A better way is do it at startWindowFullScreen(), or setUiWitStateAndScreen().
What you want are hide that when into fullscreen, nor when hit the fullscreen button, after all.

**Comment by lipangit** [comment]
extends JCVideoPlayerStandard 
override 
void setUp(){ 
    batteryTimeLayout.setVisibility(View.GONE); 
}

**Comment by fongfuse** [comment]
ok I got it. thanks!
