### ISSUE TITLE
Many memory leak

### ISSUE THREAD

**Issue by lipangit** [lipangit/JieCaoVideoPlayer#116]

**Comment by Maragues** [comment]
I've sent https://github.com/lipangit/JieCaoVideoPlayer/pull/134, but as you said there are way too many memory leaks. I don't know your experience in Android/Java development, but that needs to be reviewed thoroughly.

Leaks that I've detected and that have not been fixed

- JCMediaManager.mediaPlayer leaks a Context through its SurfaceView. You may need to call *reset()* as well as *release()* when releasing mediaPlayer, but that may leave MediaPlayer in an invalid state.
- JCVideoPlayer.JC_BURIED_POINT is declared as a field in example's MainActivity. Since it's an Anonymous inner class, it holds a reference to MainActivity

**Comment by lipangit** [comment]
This had fixed, other memery leak appear
