### ISSUE TITLE
automatically pause video

### ISSUE THREAD

**Issue by secfabregas0** [lipangit/JieCaoVideoPlayer#277]
Hello, how to pause JieCaoVideoPlayer when start new activity ( not  JCVideoPlayer.releaseAllVideos() )

**Comment by lipangit** [comment]
If this is a requirement, you should say no, we should not meet this requirement.
Because other many unnecessary requirements will incomming.

This library born to play short video (less than 20min), If your app is professional video app you should not use this library.

If you want that feature you can extends JCVideoPlayerStandard, In that class I believe you can reach your goal.

**Comment by secfabregas0** [comment]
Thanks. I paused the video with the following code: 
@Override
     protected void onPause () {
         super.onPause ();
         if (player.currentState == JCVideoPlayer.CURRENT_STATE_PLAYING) {
             player.startButton.performClick ();
         } Else if (player.currentState == JCVideoPlayer.CURRENT_STATE_PAUSE) {
             //RED CAR
         }
     }
