### ISSUE TITLE
play only voice

### ISSUE THREAD

**Issue by abbasalim** [lipangit/JieCaoVideoPlayer#427]
in the name of god
hello,
i have a problem with some videos, 
some video in my app , play only voice,and show a black screen:
 correct:
http://shahidchegini.ir/video/02%D9%85%D8%AF%D8%A7%D8%AD%DB%8C-%D8%AD%DA%A9%DB%8C%D9%85/%D8%B3%D8%AE%D9%86%D8%B1%D8%A7%D9%86%DB%8C%203225.mp4
 damaged:
http://shahidchegini.ir/video/01%d8%b3%d8%ae%d9%86%d8%b1%d8%a7%d9%86%db%8c-%d9%be%d9%86%d8%a7%d9%87%db%8c%d8%a7%d9%86%20%d8%b3%d8%a7%d9%84%2084/%d8%a7%d8%ad%d9%85%d8%af%db%8c11%20%281%29.mp4

both work in mediaplayer correct;

**Comment by lipangit** [comment]
Sorry to answer you late, I think it is a very complicated problem before.

But I try that url ,the correct url is working well , you can use that url.
https://cloud.githubusercontent.com/assets/2038071/19433445/53e83baa-9493-11e6-80ba-664f4f3f973d.png


I do not know why the damage url only voice, because the damage url in chrome is only voice too.

**Comment by abbasalim** [comment]
yes but, this have problem"
http://shahidchegini.ir/video/01%d8%b3%d8%ae%d9%86%d8%b1%d8%a7%d9%86%db%8c-%d9%be%d9%86%d8%a7%d9%87%db%8c%d8%a7%d9%86%20%d8%b3%d8%a7%d9%84%2084/%d8%a7%d8%ad%d9%85%d8%af%db%8c11%20%281%29.mp4

**Comment by lipangit** [comment]
try 5.+
