### ISSUE TITLE
Cannot change orientation after play video

### ISSUE THREAD

**Issue by RhezaSALT** [lipangit/JieCaoVideoPlayer#492]
I've followed your instructions on how to use your video player, it was a good video player. But what's wrong here is after i played your video, my apps does not want to change the orientation. When I rotate my tab into landscape, the apps still in portrait mode. Or maybe am I missing something? Thank you.

**Comment by lipangit** [comment]
![image](https://cloud.githubusercontent.com/assets/2038071/20420620/f1edd098-ad99-11e6-9065-1e08f3d30a54.png)

You can manual config these two params, that can control fullscreen origentation and quit fullscreen origentation

**Comment by moorea** [comment]
@RhezaSALT, the problem is that you need to set the Activity to let the player manage the orientation changes (this step should probably be added to the setup instructions).

In your AndroidManifest file, add the android:configChanges line like so:

`<activity android:name=".activities.MyActivity" android:configChanges="orientation|keyboardHidden|screenLayout|screenSize"/>`

Best of luck!
